all:	TreeNode DataNode IndexNode BPlusTree treesearch

TreeNode:	TreeNode.java
		javac TreeNode.java
DataNode:	DataNode.java
		javac DataNode.java
IndexNode:	IndexNode.java
		javac IndexNode.java
BPlusTree:	BPlusTree.java
		javac BPlusTree.java
treesearch:	treesearch.java
		javac treesearch.java
clean:	
		rm -rf *.class