# Gaurav Anil Yeole
# University of Florida
# COP 5536 : Advanced Data Structures
# gauravyeole@ufl.edu
# UFID 54473949


all:	TreeNode DataNode IndexNode BPlusTree treesearch

TreeNode:	TreeNode.java
		javac TreeNode.java
DataNode:	DataNode.java
		javac DataNode.java
IndexNode:	IndexNode.java
		javac IndexNode.java
BPlusTree:	BPlusTree.java
		javac BPlusTree.java
treesearch:	treesearch.java
		javac treesearch.java
clean:	
		rm -rf *.class output_file.txt